export { default as MailIcon } from './mailIcon'
export { default as LocationIcon } from './locationIcon'
export { default as XIcon } from './xIcon'
export { default as InstagramIcon } from './instagramIcon'
export { default as YoutubeIcon } from './youtubeIcon'
export { default as MenuBarsIcon } from './menuBarsIcon'
export { default as MinusIcon } from './minusIcon'
export { default as PlusIcon } from './plusIcon'
export { default as ListIcon } from './listIcon'
export { default as PlayIcon } from './playIcon'
export { default as CloseIcon } from './closeIcon'
export * from './CheckBadgeIcon'
export * from './CircularArrow'
export * from './SuccessBadgeIcon'
